apiVersion: v1
kind: ReplicationController
metadata:
  name: drone
  labels:
    name: drone
spec:
  replicas: 1
  selector:
    name: drone
  template:
    metadata:
      labels:
        name: drone
    spec:
      containers:
        - image: drone/drone:0.4
          name: drone
          env:
            # HTTP Listen Address
            - name: SERVER_ADDR
              value: ":443"
            # HTTPS private key
            #- name: SERVER_KEY
            #  value: /etc/secrets/proxykey
            #- name: SERVER_CERT
            #  value: /etc/secrets/proxycert
            # DB stuff
            - name: DATABASE_DRIVER
              value: sqlite3
            # This ends up being a mounted Google Cloud Disk.
            - name: DATABASE_CONFIG
              value: /var/lib/drone/drone.sqlite
            # RCS stuff
            #- name: REMOTE_DRIVER
            #  value: bitbucket
            # TODO: Move these into secrets.
            #- name: REMOTE_CONFIG
            #  value: https://bitbucket.org?client_id=YOUR_CLIENT_ID_HERE&client_secret=YOUR_CLIENT_SECRET_HERE&open=true
          ports:
            - containerPort: 443
              protocol: TCP
          volumeMounts:
            # Contains our SSL certs/keys
            #- mountPath: /etc/secrets
            #  name: aclima-io-ssl
            #  readOnly: true
            # Persist our configs in an SQLite DB in here
            - mountPath: /var/lib/drone
              name: drone-sqlite-db
            # Enables Docker in Docker
            - mountPath: /var/run/docker.sock
              name: docker-socket
            - mountPath: /var/lib/docker
              name: docker-lib
      volumes:
        #- name: aclima-io-ssl
        #  secret:
        #    secretName: aclima-io-ssl
        - name: drone-sqlite-db
          gcePersistentDisk:
            pdName: drone-sqlite-db
            fsType: ext4
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: docker-lib
          hostPath:
            path: /var/lib/docker
