apiVersion: v1
kind: Service
metadata:
  name: drone
  labels:
    name: drone
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    name: drone
  type: LoadBalancer
